### PR TITLE
fix(Imageview.dart): Syntax Error Issue #181

### LINKED ISSUE #181: Syntax Errors in ImageView.dart file
There are syntax errors in ImageView.dart file. I want to work on this issue as a GSSOC 21 participant.

### PR DESCRIPTION
**Pull request by SapinderSingh**
fixed syntax errors because of which app was not building. Removed redundant imports and reformatted some code.

fixed issue #181

### CODE REVIEW

**Comment by anushbhatia** [comment]
@Saransh-cpp  @arteevraina i haven't faced this issue so you guys can check and tell me if these are errors are still there.

File: lib/Imageview.dart [hunk 1]
```diff
@@ -107,130 +110,125 @@ class _ImageviewState extends State<Imageview> {
...
-                                "Back",
-                                style: TextStyle(color: Colors.white),
-                              ),
-                            ],
-                          ),
+                        },
+                        child: Column(
+                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
+                          children: <Widget>[
+                            const Icon(
```
Comment (arteevraina) [inline lib/Imageview.dart:134]: remove `const` and remove it where ever it has been repeated.

**Review by arteevraina — COMMENTED** [review]
Though the PR looks fine. I cannot see any logic change in the PR. Hope that helps.

**Comment by arteevraina** [comment]
You need to do the required changes after that I will merge this.

File: lib/Imageview.dart (hunk 1 above)
Comment (SapinderSingh) [reply lib/Imageview.dart:134]: @arteevraina I added this because of the lint rules. Is it wrong ?

Comment (arteevraina) [reply lib/Imageview.dart:134]: No, it is not wrong. But I think it can do the work without that too. Can you tell me which rules are you actually referring?

Comment (SapinderSingh) [reply lib/Imageview.dart:134]: ### Please read the last line in that box Sir

**"Prefer const with constant constructors."**

**Review by arteevraina — APPROVED** [review]
LGTM!
